export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_POSTS_BEGIN = "GET_POSTS_BEGIN";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";

export const CREATE_POST_BEGIN = "CREATE_POST_BEGIN";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";

export const CHANGE_PASS_BEGIN = "CHANGE_PASS_BEGIN";
export const CHANGE_PASS_SUCCESS = "CHANGE_PASS_SUCCESS";
export const CHANGE_PASS_ERROR = "CHANGE_PASS_ERROR";

export const SET_EDIT_POST = "SET_EDIT_POST";
export const SET_EDIT_USER = "SET_EDIT_USER";

export const EDIT_POST_BEGIN = "EDIT_POST_BEGIN";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_ERROR = "EDIT_POST_ERROR";

export const GET_PROFILE_BEGIN = "GET_PROFILE_BEGIN";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";

export const UPDATE_PROFILE_BEGIN = "UPDATE_PROFILE_BEGIN";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const GET_UPDATE_AVATAR = "GET_UPDATE_AVATAR";

export const UPDATE_MOTEL_IMAGES_SUCCESS = "UPDATE_MOTEL_IMAGES_SUCCESS";
