const comments = [
  {
    id: '1',
    author: 'DD',
    comment: 'Hello NN',
    email: 'duong@duong.com',
    status: 'approved',
    post_id: '3',
    date: '6/6/2022',
  },
  {
    id: '2',
    author: 'NN',
    comment: 'Hello CC',
    email: 'nhat@nhat.com',
    status: 'unapproved',
    post_id: '1',
    date: '6/6/2022',
  },
  {
    id: '3',
    author: 'CC',
    comment: 'Hello TT',
    email: 'chinh@chinh.com',
    status: 'unapproved',
    post_id: '4',
    date: '6/6/2022',
  },
  {
    id: '4',
    author: 'TT',
    comment: 'Hello DD',
    email: 'tuan@tuan.com',
    status: 'approved',
    post_id: '2',
    date: '6/6/2022',
  },
  {
    id: '5',
    author: 'DD',
    comment: 'Hello NN',
    email: 'duong@duong.com',
    status: 'approved',
    post_id: '3',
    date: '6/6/2022',
  },
  {
    id: '6',
    author: 'NN',
    comment: 'Hello CC',
    email: 'nhat@nhat.com',
    status: 'unapproved',
    post_id: '1',
    date: '6/6/2022',
  },
  {
    id: '7',
    author: 'CC',
    comment: 'Hello TT',
    email: 'chinh@chinh.com',
    status: 'unapproved',
    post_id: '4',
    date: '6/6/2022',
  },
  {
    id: '8',
    author: 'TT',
    comment: 'Hello DD',
    email: 'tuan@tuan.com',
    status: 'approved',
    post_id: '2',
    date: '6/6/2022',
  },
]

export default comments
