const posts = [
  {
    id: 1,
    title: 'post thu 1',
    imageUrl: 'https://i1.sndcdn.com/avatars-000600452151-38sfei-t500x500.jpg',
    description: 'Located ion with free WiFi and seating area.',
    position: 'Vung Tau',
    price: '900,000',
    area: `125m`,
    author: {
      name: 'duong',
      avaUrl: 'https://phongtro123.com/images/default-user.png',
      phone: '0123456789',
    },
    time: '9 hours ago',
    status: 'published',
    feature: 'new',
    category: 'Phong tro, nha tro',
    comments: 9,
    date: '1/1/2022',
  },
  {
    id: 2,
    title: 'Post thu 2',
    imageUrl:
      'https://i.pinimg.com/originals/58/b1/80/58b180bcba5a92d7d95c58153c9ce5b2.png',
    description: 'test post',
    position: 'Vung Tau',
    price: '1,300,000',
    area: `125m`,
    author: {
      name: 'duong',
      avaUrl: 'https://phongtro123.com/images/default-user.png',
      phone: '0123456789',
    },
    time: '9 hours ago',
    status: 'draft',
    feature: 'hot',
    category: 'Tim ban o ghep',
    comments: 5,
    date: '1/1/2022',
  },
  {
    id: 3,
    title: 'Post thu 3',
    imageUrl:
      'https://www.incimages.com/uploaded_files/image/1920x1080/getty_513189787_110007.jpg',
    description: 'Day la 1 post test',
    position: 'Vung Tau',
    price: '500,000',
    area: `125m`,
    author: {
      name: 'duong',
      avaUrl: 'https://phongtro123.com/images/default-user.png',
      phone: '0123456789',
    },
    time: '9 hours ago',
    status: 'published',
    feature: 'new',
    category: 'Phong tro, nha tro',
    comments: 1,
    date: '1/1/2022',
  },
  {
    id: 4,
    title: 'Post thu 4',
    imageUrl:
      'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/cute-cat-photos-1593441022.jpg?crop=0.669xw:1.00xh;0.166xw,0&resize=640:*',
    description:
      'Located within 550 metres of Back Beach and 1.2 km of Pineapple Beach in Vung Tau, Vung Tau Melody Apartment provides accommodation with free WiFi and seating area.',
    position: 'Vung Tau',
    price: '2,000,000',
    area: `125m`,
    author: {
      name: 'duong',
      avaUrl: 'https://phongtro123.com/images/default-user.png',
      phone: '0123456789',
    },
    time: '9 hours ago',
    status: 'published',
    feature: 'hot',
    category: 'Phong tro, nha tro',
    comments: 0,
    date: '1/1/2022',
  },
  {
    id: 5,
    title: 'post thu 5',
    imageUrl: 'https://i1.sndcdn.com/avatars-000600452151-38sfei-t500x500.jpg',
    description: 'Located ion with free WiFi and seating area.',
    position: 'Vung Tau',
    price: '650,000',
    area: `125m`,
    author: {
      name: 'duong',
      avaUrl: 'https://phongtro123.com/images/default-user.png',
      phone: '0123456789',
    },
    time: '9 hours ago',
    status: 'published',
    feature: 'new',
    category: 'Phong tro, nha tro',
    comments: 9,
    date: '1/1/2022',
  },
  {
    id: 6,
    title: 'Post thu 6',
    imageUrl:
      'https://i.pinimg.com/originals/58/b1/80/58b180bcba5a92d7d95c58153c9ce5b2.png',
    description: 'test post',
    position: 'Vung Tau',
    price: '350,000',
    area: `125m`,
    author: {
      name: 'duong',
      avaUrl: 'https://phongtro123.com/images/default-user.png',
      phone: '0123456789',
    },
    time: '9 hours ago',
    status: 'draft',
    feature: 'new',
    category: 'Tim ban o ghep',
    comments: 5,
    date: '1/1/2022',
  },
  {
    id: 7,
    title: 'Post thu 7',
    imageUrl:
      'https://www.incimages.com/uploaded_files/image/1920x1080/getty_513189787_110007.jpg',
    description: 'Day la 1 post test',
    position: 'Vung Tau',
    price: '3,500,000',
    area: `125m`,
    author: {
      name: 'duong',
      avaUrl: 'https://phongtro123.com/images/default-user.png',
      phone: '0123456789',
    },
    time: '9 hours ago',
    status: 'published',
    feature: 'hot',
    category: 'Phong tro, nha tro',
    comments: 1,
    date: '1/1/2022',
  },
  {
    id: 8,
    title: 'Post thu 8',
    imageUrl:
      'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/cute-cat-photos-1593441022.jpg?crop=0.669xw:1.00xh;0.166xw,0&resize=640:*',
    description:
      'Located within 550 metres of Back Beach and 1.2 km of Pineapple Beach in Vung Tau, Vung Tau Melody Apartment provides accommodation with free WiFi and seating area.',
    position: 'Vung Tau',
    price: '1,250,000',
    area: `125m`,
    author: {
      name: 'duong',
      avaUrl: 'https://phongtro123.com/images/default-user.png',
      phone: '0123456789',
    },
    time: '9 hours ago',
    status: 'published',
    feature: 'new',
    category: 'Phong tro, nha tro',
    comments: 0,
    date: '1/1/2022',
  },
]

export default posts
