const users = [
  {
    id: 1,
    username: 'DD',
    firstName: 'Duong',
    lastName: 'Phung',
    email: 'duong@duong.com',
    phoneNumber: '012345',
    address: '123 Nguyen Luong Bang...',
    role: 'admin',
  },
  {
    id: 2,
    username: 'NN',
    firstName: 'Nhat',
    lastName: 'Mai',
    email: 'nhat@nhat.com',
    phoneNumber: '423425',
    address: '39 Thai Phien...',
    role: 'user',
  },
  {
    id: 3,
    username: 'CC',
    firstName: 'Chinh',
    lastName: 'Chinh',
    email: 'chinh@chinh.com',
    phoneNumber: '539485',
    address: '09 Ham Nghi...',
    role: 'user',
  },
  {
    id: 4,
    username: 'TT',
    firstName: 'Tuan',
    lastName: 'Tuan',
    email: 'tuan@tuan.com',
    phoneNumber: '235435',
    address: '789 Nguyen Tat Thanh...',
    role: 'admin',
  },
  {
    id: 5,
    username: 'DD',
    firstName: 'Duong',
    lastName: 'Phung',
    email: 'duong@duong.com',
    phoneNumber: '012345',
    address: '123 Nguyen Luong Bang...',
    role: 'admin',
  },
  {
    id: 6,
    username: 'NN',
    firstName: 'Nhat',
    lastName: 'Mai',
    email: 'nhat@nhat.com',
    phoneNumber: '423425',
    address: '39 Thai Phien...',
    role: 'user',
  },
  {
    id: 7,
    username: 'CC',
    firstName: 'Chinh',
    lastName: 'Chinh',
    email: 'chinh@chinh.com',
    phoneNumber: '539485',
    address: '09 Ham Nghi...',
    role: 'user',
  },
  {
    id: 8,
    username: 'TT',
    firstName: 'Tuan',
    lastName: 'Tuan',
    email: 'tuan@tuan.com',
    phoneNumber: '235435',
    address: '789 Nguyen Tat Thanh...',
    role: 'admin',
  },
]

export default users
